name: CI

on:
  push:
    branches:
      - 'main'
      - '1.x'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.4'
            db-type: 'mysql'
            dependencies: lowest
          - php-version: '8.4'
            db-type: 'mysql'
            dependencies: highest
          - php-version: '8.4'
            db-type: 'pgsql'
            dependencies: highest
          - php-version: '8.5'
            db-type: 'mysql'
            dependencies: highest
          - php-version: '8.5'
            db-type: 'pgsql'
            dependencies: highest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: speculum_test
        ports:
          - 3306:3306
        options: --health-cmd="mysql -h 127.0.0.1 -P 3306 -u root -proot -e 'SELECT 1;'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Setup PostgreSQL
      if: matrix.db-type == 'pgsql'
      run: docker run --rm --name=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=speculum_test -p 5432:5432 -d postgres:15

    - uses: actions/checkout@v7

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_${{ matrix.db-type }}
        coverage: pcov
        ini-values: apc.enable_cli = 1, zend.assertions = 1, pcov.directory = src

    - name: Cache composer dependencies
      uses: actions/cache@v6
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

    - name: composer install
      run: |
        if [[ "${{ matrix.dependencies }}" == 'lowest' ]]; then
          composer update --prefer-lowest --prefer-stable --prefer-dist --no-progress
        else
          composer install --prefer-dist --no-progress
        fi

    - name: Setup problem matchers for PHPUnit
      if: matrix.php-version == '8.4' && matrix.db-type == 'mysql'
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Run PHPUnit with coverage
      if: matrix.php-version == '8.4' && matrix.db-type == 'mysql'
      run: |
        export CODECOVERAGE=1
        if [[ "${{ matrix.db-type }}" == 'mysql' ]]; then export db_dsn='mysql://root:root@127.0.0.1:3306/speculum_test?encoding=utf8mb4&timezone=UTC&cacheMetadata=true&quoteIdentifiers=true&persistent=false'; fi
        if [[ "${{ matrix.db-type }}" == 'pgsql' ]]; then export db_dsn='postgres://postgres:postgres@127.0.0.1:5432/speculum_test?encoding=utf8&timezone=UTC&cacheMetadata=true&quoteIdentifiers=true&persistent=false'; fi
        vendor/bin/phpunit --configuration=phpunit.xml.dist --display-deprecations --display-incomplete --display-skipped --coverage-clover=coverage.xml

    - name: Run PHPUnit without coverage
      if: matrix.php-version != '8.4' || matrix.db-type != 'mysql'
      run: |
        if [[ "${{ matrix.db-type }}" == 'mysql' ]]; then export db_dsn='mysql://root:root@127.0.0.1:3306/speculum_test?encoding=utf8mb4&timezone=UTC&cacheMetadata=true&quoteIdentifiers=true&persistent=false'; fi
        if [[ "${{ matrix.db-type }}" == 'pgsql' ]]; then export db_dsn='postgres://postgres:postgres@127.0.0.1:5432/speculum_test?encoding=utf8&timezone=UTC&cacheMetadata=true&quoteIdentifiers=true&persistent=false'; fi
        vendor/bin/phpunit --configuration=phpunit.xml.dist

    - name: Submit code coverage
      if: matrix.php-version == '8.4' && matrix.db-type == 'mysql'
      uses: codecov/codecov-action@v7

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, intl
        coverage: none

    - name: Cache composer dependencies
      uses: actions/cache@v6
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

    - name: composer install
      run: composer install --prefer-dist --no-progress

    - name: Run PHP CodeSniffer
      run: composer cs-check

    - name: Run Rector
      run: composer rector-check

    - name: Run phpstan
      run: composer stan

    - name: Run structarmed
      run: composer structarmed
